In [1]:
import torch
import torch.nn.functional as F

In [14]:
def cross_entropy_loss(y_pred, y, reduction = "mean"):
    # calculate softmax
    den = y_pred.exp().sum(axis = -1)
    num = y_pred[torch.arange(y_pred.shape[0]), y].exp()
    soft = num / den
    # apply log
    loss = soft.log()
    # avg it over all the samples
    if reduction is not None:
        loss = -loss.mean()
    return loss

In [15]:
bs = 20

In [16]:
# y_pred = torch.rand((bs, 10))
y = torch.randint(0, 10, (bs,))
y_pred.shape, y.shape

(torch.Size([20, 10]), torch.Size([20]))

In [32]:
y_pred = torch.zeros((bs, 10))
y_pred[list(range(bs)), y] = 10

In [33]:
y

tensor([3, 7, 0, 7, 3, 6, 4, 8, 3, 3, 2, 1, 5, 2, 6, 1, 3, 2, 6, 0])

In [34]:
y_pred

tensor([[ 0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,  0.],
        [10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,  0.],
        [ 0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.],
        [ 0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.],
        [ 0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.],
        [ 0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., 10.,  0.,  0.,  

In [35]:
cross_entropy_loss(y_pred, y, None)

tensor([-0.0004, -0.0004, -0.0004, -0.0004, -0.0004, -0.0004, -0.0004, -0.0004,
        -0.0004, -0.0004, -0.0004, -0.0004, -0.0004, -0.0004, -0.0004, -0.0004,
        -0.0004, -0.0004, -0.0004, -0.0004])

In [29]:
def cross_entropy_loss_faster(y_pred, y):
    log_probs = F.log_softmax(y_pred, dim=1)
    loss = -log_probs[torch.arange(y.shape[0]), y].mean()
    return loss

In [30]:
cross_entropy_loss_faster(y_pred, y)

tensor(1.4612)