In [10]:
import sys
sys.path.insert(0, '..')
from tokenizer.tokenizer import Tokenizer
import torch
from docling.document_converter import DocumentConverter

# None of the existing methods are working dfine for Hindi data extraction, so did it manully, by copying and pasting in a txt file

## Docling

In [26]:
%%time
source = "../data/Valmiki Ramayan (Sanskrit Classics) (Hindi)-short.pdf"  # document per local path or URL
converter = DocumentConverter()
result = converter.convert(source)

CPU times: user 5.72 s, sys: 500 ms, total: 6.22 s
Wall time: 3.98 s


In [27]:
a = result.document.export_to_text()

In [29]:
with open("docling.txt", "w") as file:
    file.write(a)

## pymupdf

In [8]:
import fitz

In [9]:
file =  fitz.open(source)

## pypdf2

In [18]:
from PyPDF2 import PdfReader

In [20]:
reader = PdfReader(source)
for page in reader.pages:
    print(page.extract_text())

ᱨपा᭠तरकार
आन᭠दकुमार
ISBN : 9788170284901
ᮧथम
 
सं᭭करण
 : 2016 © 
राजपाल
 
ए᭛ड
 
स᭠ज़
VALMIKI RAMAYAN (Sanskrit Epic) by Valmiki
राजपाल
 
ए᭛ड
 
स᭠ज़
1590, 
मदरसा
 
रोड
, 
क᭫मीरी
 
गेट
-
ᳰद᭨ली
-110006
फोन
: 011-23869812, 23865483, 
फै᭍स
: 011-23867791
website: 
www.rajpalpublishing.com
e-mail : 
sales@rajpalpublishing.com
ᮓम
1. 
रामायण
 
कᳱ
 
ᮧ᭭तावना
आदशᭅ
 
पुᱧष
 
कौन
 
है
?
; 
का᳞
 
कᳱ
 
उ᭜पिᱫ
; 
किव
 
कᳱ
 
साधना
; 
रामायण
 
का
 
ᮧचार
।
2. 
बालका᭛ड
अयो᭟या
 
का
 
वैभव
; 
दशरथ
 
का
 
ऐ᳡यᭅ
; 
पुᮢेि᳥
-
य᭄
; 
राम
-
ज᭠म
; 
कुमारᲂ
 
कᳱ
 
िशᭃा
-
दीᭃा
; 
िव᳡ािमᮢ
 
का
 
आगमन
; 
ताड़का
-
वध
; 
िस᳍ा᮰म
-
याᮢा
; 
िमिथला
 
कᳱ
 
याᮢा
;
अह᭨यो᳍ार
; 
धनुभᲈग
, 
राम
-
सीता
 
का
 
िववाह
; 
राम
-
परशुराम
 
िववाद
।
3. 
अयो᭟याका᭛ड
जनगणमन
-
अिधनायक
 
राम
; 
रामािभषेक
 
का
 
ᮧ᭭ताव
; 
म᭠थरा
 
कᳱ
 
कुम᭠ᮢणा
; 
रंग
 
मᱶ
भंग
; 
ऋिषपथ
 
पर
 
ᮧ᭭थान
; 
अयो᭟या
 
मᱶ
 
हाहाकार
; 
भरत
 
कᳱ
 
िचᮢकूट
-
याᮢा
; 
राम
 
का
िचᮢकूट
 
से
 
ᮧ᭭थान
।
4. 
अर᭛यका᭛ड
द᭛डकार᭛य
 
मᱶ
 
ᮧवेश
; 
िवराध
-
वध
; 
दिᭃण
 
के
 
आ᮰मᲂ
 
का
 
िनरीᭃण
; 
राम
-

## pdfplumber

In [22]:
import pdfplumber

In [24]:
pdf = pdfplumber.open(source)

In [25]:
for page in pdf.pages:
    print(page.extract_text())

(cid:7272)पा(cid:7008)तरकार
आन(cid:7008)दकुमार
ISBN : 9788170284901
(cid:7079)थम सं(cid:7021)करण : 2016 © राजपाल ए(cid:7003)ड स(cid:7008)ज़
VALMIKI RAMAYAN (Sanskrit Epic) by Valmiki
राजपाल ए(cid:7003)ड स(cid:7008)ज़
1590, मदरसा रोड, क(cid:7019)मीरी गेट-(cid:7408)द(cid:7016)ली-110006
फोन: 011-23869812, 23865483, फै(cid:6989)स: 011-23867791
website: www.rajpalpublishing.com
e-mail : sales@rajpalpublishing.com
(cid:7059)म
1. रामायण क(cid:7409) (cid:7079)(cid:7021)तावना
आदश(cid:6981) पु(cid:7271)ष कौन ह?ै ; का(cid:7390) क(cid:7409) उ(cid:7004)पि(cid:7275); किव क(cid:7409) साधना; रामायण का (cid:7079)चार।
2. बालका(cid:7003)ड
अयो(cid:7007)या का वैभव; दशरथ का ऐ(cid:7393)य(cid:6981); पु(cid:7074)ेि(cid:7397)-य(cid:6980); राम-ज(cid:7008)म; कुमार(cid:7298) क(cid:7409) िश(cid:6979)ा-
दी(cid:6979)ा; िव(cid:7393)ािम(cid:7074) का आगमन; ताड़का-वध; िस(cid:7373)ा(cid:7088)म-या(cid:7074)ा; िमिथला क(cid:7409) या(cid:7074)ा;
अह(cid:7016)यो(cid:7373)ार; धनुभ(cid:7304)ग, राम-सीता का िववाह; राम-परशुराम िववाद।
3

# Create vocabulary

In [ ]:
# with open("../data/ramayana.txt", "r") as file:
#     data = file.read()

# len(data)

# tokenizer = Tokenizer()

# %%time
# tokenizer.train(data, 10000, "ramayana_hindi")

In [11]:
tokenizer = Tokenizer()
tokenizer.from_pretrained("./ramayana_hindi.json")

Vocabulary has been built internally of length 10000, ready to encode and decode


In [12]:
# check if encoding and decoding works as expected
tokenizer.decode(tokenizer.encode("हैलो, क्या हाल हैं?"))

Length of raw bytes: 47
Length of final merged bytes: 16


'हैलो, क्या हाल हैं?'

In [13]:
text_data = open("../data/ramayana.txt", "r").read()
data = torch.tensor(tokenizer.encode(text_data))
len(text_data), len(data)

Length of raw bytes: 552381
Length of final merged bytes: 52933


(230524, 52933)

In [23]:
data.shape

torch.Size([52933])

In [14]:
block_size = 8

In [29]:
batch_data = data[:block_size + 1]
xb = batch_data[:block_size]
yb = batch_data[1:]

In [32]:
len(xb), len(yb)

(8, 8)

In [34]:
print(xb)
print(yb)

tensor([4877,  291, 1191,   10,   10, 3366, 6602,  427])
tensor([ 291, 1191,   10,   10, 3366, 6602,  427, 1511])


In [33]:
for i in range(block_size):
    print(f"Contenxt is: {xb[:i + 1]}, Target is: {yb[i]}")

Contenxt is: tensor([4877]), Target is: 291
Contenxt is: tensor([4877,  291]), Target is: 1191
Contenxt is: tensor([4877,  291, 1191]), Target is: 10
Contenxt is: tensor([4877,  291, 1191,   10]), Target is: 10
Contenxt is: tensor([4877,  291, 1191,   10,   10]), Target is: 3366
Contenxt is: tensor([4877,  291, 1191,   10,   10, 3366]), Target is: 6602
Contenxt is: tensor([4877,  291, 1191,   10,   10, 3366, 6602]), Target is: 427
Contenxt is: tensor([4877,  291, 1191,   10,   10, 3366, 6602,  427]), Target is: 1511


In [26]:
train_data = data[:int(0.9*len(data))]
val_data = data[int(0.9*len(data)):]
print(f"Len of train data: {len(train_data)}, Len of val data: {len(val_data)}")

Len of train data: 47639, Len of val data: 5294


In [55]:
torch.manual_seed(42)
batch_size = 4
def get_batch(batch_size = batch_size, data_type = "train"):
    data = train_data if data_type == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    print(ix)
    xb = torch.stack([data[i : i + block_size] for i in ix])
    yb = torch.stack([data[i + 1 : i + 1 + block_size] for i in ix])
    return xb, yb

In [56]:
xb, yb = get_batch()

tensor([43410, 29492, 24139, 29674])


In [57]:
print(xb)
print(yb)

tensor([[3601,  257, 2309,  302, 1631, 6048, 3814,  440],
        [ 334, 4042, 2733,   44, 2449, 1773, 4087,  848],
        [ 425, 3120,  156,  299, 1279, 1288,  268, 9066],
        [ 301,  459,  257, 3890, 1015,  287, 6178,  334]])
tensor([[ 257, 2309,  302, 1631, 6048, 3814,  440, 5123],
        [4042, 2733,   44, 2449, 1773, 4087,  848,  332],
        [3120,  156,  299, 1279, 1288,  268, 9066, 1451],
        [ 459,  257, 3890, 1015,  287, 6178,  334, 6401]])


In [60]:
for row in range(batch_size):
    for i in range(1, block_size):
        print(f"Context is : {xb[row][:i]} Target is : {yb[row][i]}")

Context is : tensor([3601]) Target is : 2309
Context is : tensor([3601,  257]) Target is : 302
Context is : tensor([3601,  257, 2309]) Target is : 1631
Context is : tensor([3601,  257, 2309,  302]) Target is : 6048
Context is : tensor([3601,  257, 2309,  302, 1631]) Target is : 3814
Context is : tensor([3601,  257, 2309,  302, 1631, 6048]) Target is : 440
Context is : tensor([3601,  257, 2309,  302, 1631, 6048, 3814]) Target is : 5123
Context is : tensor([334]) Target is : 2733
Context is : tensor([ 334, 4042]) Target is : 44
Context is : tensor([ 334, 4042, 2733]) Target is : 2449
Context is : tensor([ 334, 4042, 2733,   44]) Target is : 1773
Context is : tensor([ 334, 4042, 2733,   44, 2449]) Target is : 4087
Context is : tensor([ 334, 4042, 2733,   44, 2449, 1773]) Target is : 848
Context is : tensor([ 334, 4042, 2733,   44, 2449, 1773, 4087]) Target is : 332
Context is : tensor([425]) Target is : 156
Context is : tensor([ 425, 3120]) Target is : 299
Context is : tensor([ 425, 3120,